// Code generated by hands for test DO NOT EDIT.
// hogehoge

package a

import (
	"context"

	"go.opencensus.io/trace"
)

func L(ctx context.Context) {
	trace.StartSpan(ctx, "a.F")
}

func M(ctx context.Context) {
}

func N(ctx context.Context) {
	trace.StartSpan(ctx, "a.F")
}

func (h *Hoge) Func3(ctx context.Context) {
	trace.StartSpan(ctx, "(*a.Hoge).Func")
}

func (h *Hoge) Fail3(ctx context.Context) {
}

func (h Fuga) Func3(ctx context.Context) {
	trace.StartSpan(ctx, "(a.Fuga).Func")
}

func (h Fuga) Fail3(ctx context.Context) {
}
